# Plex Media Server

services:
  plex:
    image: ${PLEX_IMAGE}:${PLEX_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PLEX_UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_DIR}/config/plex-config:/config
      - ${ROOT_DIR}/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:32400/identity && test -d /data/realdebrid-zurg && mountpoint -q /data/realdebrid-zurg"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      overseerr:
        condition: service_healthy
        restart: true
      rclone:
        condition: service_healthy
        restart: true