# Prowlarr - Indexer Management

services:
  prowlarr:
    image: ${PROWLARR_IMAGE}:${PROWLARR_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: prowlarr
    cpus: 0.5
    networks:
      mediacenter:
        ipv4_address: 172.30.0.10
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--connect-timeout", "3", "http://localhost:9696/ping"]
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    environment:
    - PUID=${PROWLARR_UID}
    - PGID=${MEDIACENTER_GID}
    - UMASK=002
    - TZ=${TIMEZONE}
    tmpfs:
    - /tmp:mode=770,noexec,size=30M,uid=${PROWLARR_UID},gid=${MEDIACENTER_GID}
    - /logs:mode=770,size=50M,uid=${PROWLARR_UID},gid=${MEDIACENTER_GID}
    volumes:
    - ${ROOT_DIR}/config/prowlarr-config:/config
    ports:
    - ${PROWLARR_PORT}:9696
    restart: on-failure:5
    logging:
      driver: local
      options:
        max-file: '5'
        max-size: 10m
    labels:
    - traefik.enable=true
    - traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.prowlarr.entrypoints=web
    - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    depends_on:
      decypharr:
        condition: service_healthy
        restart: true
